name: create conda environments

on:
  pull_request:
    paths:
      - '.github/workflows/create-conda-envs.yml'
      - '.github/actions/create-conda-envs/*'
      - 'src/reference/environments/env/*.ya?ml'
  workflow_dispatch:
    inputs:
      cylc_flow_version:
        description: 'Version to install.'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_conda_install:
    # Workflow is currently broken
    # https://github.com/cylc/cylc-doc/pull/788#issuecomment-2573610197
    if: false
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python: ['3.x']
    steps:
      - name: checkout cylc-doc
        uses: actions/checkout@v5

      - name: configure python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: install setuptools
        run: |
          # pick up deps for version processing
          pip install 'setuptools>=50'

      - name: checkout cylc-flow init file
        run: |
          # needed to extract the cylc-flow version
          LIB_PATH='src/lib/cylc/flow'
          mkdir -p "$LIB_PATH"
          curl \
            https://raw.githubusercontent.com/cylc/cylc-flow/master/cylc/flow/__init__.py \
            > "$LIB_PATH/__init__.py"

      - name: create conda envs
        uses: ./.github/actions/create-conda-envs
        with:
          python_version: ${{ matrix.python }}
          cylc_flow_version: ${{ github.event.inputs.cylc_flow_version }}
