# THIS FILE IS PART OF THE CYLC WORKFLOW ENGINE.
# Copyright (C) NIWA & British Crown (Met Office) & Contributors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Remove a deployed version of the documentation.

# Note: All changes made to the gh-pages branch are non-destructive
#       (i.e. no force pushing) so all changes can be undone.

name: undeploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag present on both cylc-flow and cylc-docs.'
        required: true

jobs:
  undeploy:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    env:
      TAG: ${{ github.event.inputs.tag }}
    steps:
      - name: configure python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: checkout cylc-doc
        uses: actions/checkout@v2

      - name: checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: check tag
        run: |
          for ver in stable latest; do
            ver_link="$(readlink gh-pages/${ver})"
            if [[ -z "$ver_link" ]]
            then
              echo "::error::Could not determine the '"$ver"' version"
              exit 1
            elif [[ "$ver" == "$TAG" ]]
            then
              echo "::error::Cannot delete the '"$ver"' version"
              exit 1
            fi
          done

      - name: configure git
        uses: cylc/release-actions/configure-git@v1

      - name: remove version
        working-directory: gh-pages
        run: |
          git rm -r "$TAG"

      - name: update version file
        run: |
          bin/version write

      - name: push changes
        working-directory: gh-pages
        run: |
          git add -u
          git commit -m "remove: ${TAG}"
          git push origin HEAD
